version: '3' # composeファイルのバージョン
services:
  backend: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./Dockerfile
    command: air
    volumes: # マウントディレクトリ
      - ./app:/usr/src/app
    tty: true # コンテナの永続化
    stdin_open: true
    # env_file: # .envファイル
    #   - ./build/.go_env
    ports:
      - "1323:1323"
    environment:
      - TZ=Asia/Tokyo
  front: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    working_dir: /usr/src/app/frontend/
    volumes: # マウントディレクトリ
      - ./app/frontend:/usr/src/app/frontend/
    tty: true # コンテナの永続化
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local