import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import ThemeToggle from "@/components/ThemeToggle";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// React がマウントされる前に dark クラスを当てて、初回描画のちらつきを防ぐ
const themeScript = `
(function () {
  try {
    var saved = localStorage.getItem('theme');
    var theme = (saved === 'light' || saved === 'dark' || saved === 'system') ? saved : 'system';
    var isDark = theme === 'dark' ||
      (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
    if (isDark) {
      document.documentElement.classList.add('dark');
    }
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const HederComponent = () => {
    return (
      <div className='header h-14 bg-teal-300 border-black sticky top-0 z-40 flex items-center justify-between px-2 dark:bg-teal-800'>
        <h1 className='text-slate-50 font-bold text-3xl'>
          <Link href='/'>@SmartDemo</Link>
        </h1>
        <ThemeToggle />
      </div>
    )
  }

  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={inter.className}>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <HederComponent />
        {children}
      </body>
    </html>
  );
}
